### ISSUE TITLE
JavaScript errors in the console -- JS does not funciton

### ISSUE THREAD

**Issue by andreimoment** [lazaronixon/the_construct#2]
Just created a new app from the template and when starting Rails, got these errors. Any idea of what might resolve them?

~~~
Uncaught TypeError: __webpack_require__(...) is not a function
    at Module../node_modules/webpack/buildin/harmony-module.js (harmony-module.js:33)
    at __webpack_require__ (bootstrap:19)
    at Module../node_modules/webpack/buildin/global.js (global.js:23)
    at __webpack_require__ (bootstrap:19)
    at Object../node_modules/core-js-pure/internals/global.js (global.js:14)
    at __webpack_require__ (bootstrap:19)
    at Object../node_modules/core-js-pure/internals/well-known-symbol.js (well-known-symbol.js:1)
    at __webpack_require__ (bootstrap:19)
    at Object../node_modules/core-js-pure/internals/wrapped-well-known-symbol.js (wrapped-well-known-symbol.js:1)
    at __webpack_require__ (bootstrap:19)
~~~

**Comment by crova** [comment]
I got the same behavior here.
Log shows the same NoMethodError for all 4 console errors.

Log shows (for the last console error, from iziToast):
```
14:11:45 web.1    | 2019-06-07 14:11:45 +0200: Rack app error handling request { GET /assets/izitoast/dist/css/iziToast.self-121ca6cd024370b096bd7d5fc
d6c841426824a5697f916c62396d032710e9213.css }                                                                                                         
14:11:45 web.1    | #<NoMethodError: undefined method `execute_if_updated' for nil:NilClass>                                                          
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionview-6.0.0.rc1/lib/action_view/cache_expiry.rb:30:in `clear_cache_if_necessary'       
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionview-6.0.0.rc1/lib/action_view/cache_expiry.rb:11:in `before'                         
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:429:in `block in make_lambda'       
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:607:in `block (2 levels) in default_
terminator'                                                                                                                                           
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:606:in `catch'                      
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:606:in `block in default_terminator'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:202:in `block in halting'           
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:514:in `block in invoke_before'     
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:514:in `each'                       
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:514:in `invoke_before'              
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:134:in `run_callbacks'              
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/execution_wrapper.rb:111:in `run!'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/execution_wrapper.rb:73:in `block in run!'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/execution_wrapper.rb:70:in `tap'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/execution_wrapper.rb:70:in `run!'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/executor.rb:12:in `call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:57:in `block in call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/notifications.rb:182:in `instrument'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:56:in `call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/static.rb:126:in `call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:57:in `block in call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/notifications.rb:182:in `instrument'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:56:in `call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:57:in `block in call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/notifications.rb:182:in `instrument'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:56:in `call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:57:in `block in call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/notifications.rb:182:in `instrument'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:56:in `call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/webpacker-4.0.7/lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:57:in `block in call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.rc1/lib/active_support/notifications.rb:182:in `instrument'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/actionpack-6.0.0.rc1/lib/action_dispatch/middleware/stack.rb:56:in `call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/railties-6.0.0.rc1/lib/rails/engine.rb:526:in `call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
14:11:45 web.1    | /home/crova/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

I didn't have time to look further but I'll dig when I can.

**Comment by LemonAndroid** [comment]
Join our discord if you want live help 

https://discord.gg/RtUvAxU
